Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "docker-example"
  config.vm.provision "shell", path: "docker-bootstrap.sh"
  config.vm.network :private_network, ip: "192.168.16.10"
end
