Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
  config.vm.box = "ubuntu/xenial64"
  (1..5).each do |i|
    config.vm.define "web#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.50.#{10+i}"
      node.vm.network "forwarded_port", guest: 80, host: "#{8000+i}"
      node.vm.provision  "shell", path: "bootstrap.sh"
    end
  end
end
