- hosts: all
  become: true
  tasks:
    - name: Install nginx.
      apt: name={{ item }} state=present
      with_items:
      - nginx

    - name: Clean artifact path
      file:
        state: absent
        path: /var/www/html
