Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
    config.vm.define "dev" do |dev|
        dev.vm.hostname = "dev.site"
        dev.vm.network :private_network, ip: "192.168.16.10"
        dev.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
        dev.vm.network :forwarded_port, guest: 22, host: 4444, auto_correct: true
        dev.vm.network :forwarded_port, guest: 80, host: 8010, auto_correct: true
        dev.vm.provision  "shell", path: "bootstrap_dev.sh"
    end
    config.vm.define "uat" do |uat|
        uat.vm.hostname = "uat.site"
        uat.vm.network :private_network, ip: "192.168.16.11"
        uat.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
        uat.vm.network :forwarded_port, guest: 22, host: 5555, auto_correct: true
        uat.vm.network :forwarded_port, guest: 80, host: 8011, auto_correct: true
        uat.vm.provision  "shell", path: "bootstrap_uat.sh"
    end
    config.vm.define "prod" do |prod|
        prod.vm.hostname = "prod.site"
        prod.vm.network :private_network, ip: "192.168.16.12"
        prod.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
        prod.vm.network :forwarded_port, guest: 22, host: 6666, auto_correct: true
        prod.vm.network :forwarded_port, guest: 80, host: 8012, auto_correct: true
        prod.vm.provision  "shell", path: "bootstrap_prod.sh"
    end
end
